"""empty message

Revision ID: 644808036e59
Revises: cc7648a89e5d
Create Date: 2018-10-16 12:34:26.486028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644808036e59'
down_revision = 'cc7648a89e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('dateAdded', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'dateAdded')
    # ### end Alembic commands ###
